I0910 15:39:47.900299 135461134128960 __init__.py:88] MUJOCO_GL=egl, attempting to import specified OpenGL backend.
I0910 15:39:47.909821 135461134128960 acceleratesupport.py:24] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
I0910 15:39:48.042429 135461134128960 __init__.py:31] MuJoCo library version is: 3.3.5
load datafile: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 17.39it/s]
load datafile: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 814.49it/s]
load datafile: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 178.37it/s]
load datafile: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 1517.38it/s]
  0%|                                                                                                                    | 0/1500000 [00:00<?, ?it/s]
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m_bobrin/infom/main.py", line 277, in <module>
    app.run(main)
  File "/home/m_bobrin/miniconda3/envs/infom1/lib/python3.10/site-packages/absl/app.py", line 316, in run
    _run_main(main, args)
  File "/home/m_bobrin/miniconda3/envs/infom1/lib/python3.10/site-packages/absl/app.py", line 261, in _run_main
    sys.exit(main(argv))
  File "/home/m_bobrin/infom/main.py", line 146, in main
    agent, update_info = agent.pretrain(batch)
  File "/home/m_bobrin/infom/agents/fb_repr.py", line 369, in pretrain
    new_network, info = self.network.apply_loss_fn(loss_fn=loss_fn)
  File "/home/m_bobrin/infom/utils/flax_utils.py", line 137, in apply_loss_fn
    grads, info = jax.grad(loss_fn, has_aux=True)(self.params)
  File "/home/m_bobrin/infom/agents/fb_repr.py", line 367, in loss_fn
    return self.pretraining_loss(batch, grad_params, rng=rng)
  File "/home/m_bobrin/infom/agents/fb_repr.py", line 320, in pretraining_loss
    fb_actor_loss, fb_actor_info = self.forward_backward_actor_loss(batch, grad_params, actor_rng)
  File "/home/m_bobrin/infom/agents/fb_repr.py", line 245, in forward_backward_actor_loss
    if self.config['actor_repr']['normalize_q_loss']:
  File "/home/m_bobrin/miniconda3/envs/infom1/lib/python3.10/site-packages/flax/core/frozen_dict.py", line 70, in __getitem__
    v = self._dict[key]
KeyError: 'actor_repr'
